/* Generated by Yosys 0.55+158 (git sha1 fd2ea51e1, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "single_port_ram.v:1.1-19.10" *)
module single_port_ram(clk, we, addr, din, dout);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  (* src = "single_port_ram.v:7.33-7.37" *)
  input [3:0] addr;
  wire [3:0] addr;
  (* src = "single_port_ram.v:5.16-5.19" *)
  input clk;
  wire clk;
  (* src = "single_port_ram.v:8.33-8.36" *)
  input [7:0] din;
  wire [7:0] din;
  (* src = "single_port_ram.v:9.33-9.37" *)
  output [7:0] dout;
  reg [7:0] dout;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[10] ;
  reg [7:0] \mem[11] ;
  reg [7:0] \mem[12] ;
  reg [7:0] \mem[13] ;
  reg [7:0] \mem[14] ;
  reg [7:0] \mem[15] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  reg [7:0] \mem[8] ;
  reg [7:0] \mem[9] ;
  (* src = "single_port_ram.v:6.16-6.18" *)
  input we;
  wire we;
  assign _017_ = addr[0] ? \mem[1] [0] : \mem[0] [0];
  assign _018_ = addr[0] ? \mem[3] [0] : \mem[2] [0];
  assign _019_ = addr[1] ? _018_ : _017_;
  assign _020_ = addr[0] ? \mem[5] [0] : \mem[4] [0];
  assign _021_ = addr[0] ? \mem[7] [0] : \mem[6] [0];
  assign _022_ = addr[1] ? _021_ : _020_;
  assign _023_ = addr[2] ? _022_ : _019_;
  assign _024_ = addr[0] ? \mem[9] [0] : \mem[8] [0];
  assign _025_ = addr[0] ? \mem[11] [0] : \mem[10] [0];
  assign _026_ = addr[1] ? _025_ : _024_;
  assign _027_ = addr[0] ? \mem[13] [0] : \mem[12] [0];
  assign _028_ = addr[0] ? \mem[15] [0] : \mem[14] [0];
  assign _029_ = addr[1] ? _028_ : _027_;
  assign _030_ = addr[2] ? _029_ : _026_;
  assign _000_[0] = addr[3] ? _030_ : _023_;
  assign _031_ = addr[0] ? \mem[1] [1] : \mem[0] [1];
  assign _032_ = addr[0] ? \mem[3] [1] : \mem[2] [1];
  assign _033_ = addr[1] ? _032_ : _031_;
  assign _034_ = addr[0] ? \mem[5] [1] : \mem[4] [1];
  assign _035_ = addr[0] ? \mem[7] [1] : \mem[6] [1];
  assign _036_ = addr[1] ? _035_ : _034_;
  assign _037_ = addr[2] ? _036_ : _033_;
  assign _038_ = addr[0] ? \mem[9] [1] : \mem[8] [1];
  assign _039_ = addr[0] ? \mem[11] [1] : \mem[10] [1];
  assign _040_ = addr[1] ? _039_ : _038_;
  assign _041_ = addr[0] ? \mem[13] [1] : \mem[12] [1];
  assign _042_ = addr[0] ? \mem[15] [1] : \mem[14] [1];
  assign _043_ = addr[1] ? _042_ : _041_;
  assign _044_ = addr[2] ? _043_ : _040_;
  assign _000_[1] = addr[3] ? _044_ : _037_;
  assign _045_ = addr[0] ? \mem[1] [2] : \mem[0] [2];
  assign _046_ = addr[0] ? \mem[3] [2] : \mem[2] [2];
  assign _047_ = addr[1] ? _046_ : _045_;
  assign _048_ = addr[0] ? \mem[5] [2] : \mem[4] [2];
  assign _049_ = addr[0] ? \mem[7] [2] : \mem[6] [2];
  assign _050_ = addr[1] ? _049_ : _048_;
  assign _051_ = addr[2] ? _050_ : _047_;
  assign _052_ = addr[0] ? \mem[9] [2] : \mem[8] [2];
  assign _053_ = addr[0] ? \mem[11] [2] : \mem[10] [2];
  assign _054_ = addr[1] ? _053_ : _052_;
  assign _055_ = addr[0] ? \mem[13] [2] : \mem[12] [2];
  assign _056_ = addr[0] ? \mem[15] [2] : \mem[14] [2];
  assign _057_ = addr[1] ? _056_ : _055_;
  assign _058_ = addr[2] ? _057_ : _054_;
  assign _000_[2] = addr[3] ? _058_ : _051_;
  assign _059_ = addr[0] ? \mem[1] [3] : \mem[0] [3];
  assign _060_ = addr[0] ? \mem[3] [3] : \mem[2] [3];
  assign _061_ = addr[1] ? _060_ : _059_;
  assign _062_ = addr[0] ? \mem[5] [3] : \mem[4] [3];
  assign _063_ = addr[0] ? \mem[7] [3] : \mem[6] [3];
  assign _064_ = addr[1] ? _063_ : _062_;
  assign _065_ = addr[2] ? _064_ : _061_;
  assign _066_ = addr[0] ? \mem[9] [3] : \mem[8] [3];
  assign _067_ = addr[0] ? \mem[11] [3] : \mem[10] [3];
  assign _068_ = addr[1] ? _067_ : _066_;
  assign _069_ = addr[0] ? \mem[13] [3] : \mem[12] [3];
  assign _070_ = addr[0] ? \mem[15] [3] : \mem[14] [3];
  assign _071_ = addr[1] ? _070_ : _069_;
  assign _072_ = addr[2] ? _071_ : _068_;
  assign _000_[3] = addr[3] ? _072_ : _065_;
  assign _073_ = addr[0] ? \mem[1] [4] : \mem[0] [4];
  assign _074_ = addr[0] ? \mem[3] [4] : \mem[2] [4];
  assign _075_ = addr[1] ? _074_ : _073_;
  assign _076_ = addr[0] ? \mem[5] [4] : \mem[4] [4];
  assign _077_ = addr[0] ? \mem[7] [4] : \mem[6] [4];
  assign _078_ = addr[1] ? _077_ : _076_;
  assign _079_ = addr[2] ? _078_ : _075_;
  assign _080_ = addr[0] ? \mem[9] [4] : \mem[8] [4];
  assign _081_ = addr[0] ? \mem[11] [4] : \mem[10] [4];
  assign _082_ = addr[1] ? _081_ : _080_;
  assign _083_ = addr[0] ? \mem[13] [4] : \mem[12] [4];
  assign _084_ = addr[0] ? \mem[15] [4] : \mem[14] [4];
  assign _085_ = addr[1] ? _084_ : _083_;
  assign _086_ = addr[2] ? _085_ : _082_;
  assign _000_[4] = addr[3] ? _086_ : _079_;
  assign _087_ = addr[0] ? \mem[1] [5] : \mem[0] [5];
  assign _088_ = addr[0] ? \mem[3] [5] : \mem[2] [5];
  assign _089_ = addr[1] ? _088_ : _087_;
  assign _090_ = addr[0] ? \mem[5] [5] : \mem[4] [5];
  assign _091_ = addr[0] ? \mem[7] [5] : \mem[6] [5];
  assign _092_ = addr[1] ? _091_ : _090_;
  assign _093_ = addr[2] ? _092_ : _089_;
  assign _094_ = addr[0] ? \mem[9] [5] : \mem[8] [5];
  assign _095_ = addr[0] ? \mem[11] [5] : \mem[10] [5];
  assign _096_ = addr[1] ? _095_ : _094_;
  assign _097_ = addr[0] ? \mem[13] [5] : \mem[12] [5];
  assign _098_ = addr[0] ? \mem[15] [5] : \mem[14] [5];
  assign _099_ = addr[1] ? _098_ : _097_;
  assign _100_ = addr[2] ? _099_ : _096_;
  assign _000_[5] = addr[3] ? _100_ : _093_;
  assign _101_ = addr[0] ? \mem[1] [6] : \mem[0] [6];
  assign _102_ = addr[0] ? \mem[3] [6] : \mem[2] [6];
  assign _103_ = addr[1] ? _102_ : _101_;
  assign _104_ = addr[0] ? \mem[5] [6] : \mem[4] [6];
  assign _105_ = addr[0] ? \mem[7] [6] : \mem[6] [6];
  assign _106_ = addr[1] ? _105_ : _104_;
  assign _107_ = addr[2] ? _106_ : _103_;
  assign _108_ = addr[0] ? \mem[9] [6] : \mem[8] [6];
  assign _109_ = addr[0] ? \mem[11] [6] : \mem[10] [6];
  assign _110_ = addr[1] ? _109_ : _108_;
  assign _111_ = addr[0] ? \mem[13] [6] : \mem[12] [6];
  assign _112_ = addr[0] ? \mem[15] [6] : \mem[14] [6];
  assign _113_ = addr[1] ? _112_ : _111_;
  assign _114_ = addr[2] ? _113_ : _110_;
  assign _000_[6] = addr[3] ? _114_ : _107_;
  assign _115_ = addr[0] ? \mem[1] [7] : \mem[0] [7];
  assign _116_ = addr[0] ? \mem[3] [7] : \mem[2] [7];
  assign _117_ = addr[1] ? _116_ : _115_;
  assign _118_ = addr[0] ? \mem[5] [7] : \mem[4] [7];
  assign _119_ = addr[0] ? \mem[7] [7] : \mem[6] [7];
  assign _120_ = addr[1] ? _119_ : _118_;
  assign _121_ = addr[2] ? _120_ : _117_;
  assign _122_ = addr[0] ? \mem[9] [7] : \mem[8] [7];
  assign _123_ = addr[0] ? \mem[11] [7] : \mem[10] [7];
  assign _124_ = addr[1] ? _123_ : _122_;
  assign _125_ = addr[0] ? \mem[13] [7] : \mem[12] [7];
  assign _126_ = addr[0] ? \mem[15] [7] : \mem[14] [7];
  assign _127_ = addr[1] ? _126_ : _125_;
  assign _128_ = addr[2] ? _127_ : _124_;
  assign _000_[7] = addr[3] ? _128_ : _121_;
  assign _129_ = addr[0] | addr[1];
  assign _130_ = addr[2] | addr[3];
  assign _131_ = _130_ | _129_;
  assign _001_ = we & ~(_131_);
  assign _132_ = addr[1] | ~(addr[0]);
  assign _133_ = _132_ | _130_;
  assign _008_ = we & ~(_133_);
  assign _134_ = addr[0] | ~(addr[1]);
  assign _135_ = _134_ | _130_;
  assign _009_ = we & ~(_135_);
  assign _136_ = ~(addr[0] & addr[1]);
  assign _137_ = _136_ | _130_;
  assign _010_ = we & ~(_137_);
  assign _138_ = addr[3] | ~(addr[2]);
  assign _139_ = _138_ | _129_;
  assign _011_ = we & ~(_139_);
  assign _140_ = _138_ | _132_;
  assign _012_ = we & ~(_140_);
  assign _141_ = _138_ | _134_;
  assign _013_ = we & ~(_141_);
  assign _142_ = _138_ | _136_;
  assign _014_ = we & ~(_142_);
  assign _143_ = addr[2] | ~(addr[3]);
  assign _144_ = _143_ | _129_;
  assign _015_ = we & ~(_144_);
  assign _145_ = _143_ | _132_;
  assign _016_ = we & ~(_145_);
  assign _146_ = _143_ | _134_;
  assign _002_ = we & ~(_146_);
  assign _147_ = _143_ | _136_;
  assign _003_ = we & ~(_147_);
  assign _148_ = ~(addr[2] & addr[3]);
  assign _149_ = _148_ | _129_;
  assign _004_ = we & ~(_149_);
  assign _150_ = _148_ | _132_;
  assign _005_ = we & ~(_150_);
  assign _151_ = _148_ | _134_;
  assign _006_ = we & ~(_151_);
  assign _152_ = _148_ | _136_;
  assign _007_ = we & ~(_152_);
  always @(posedge clk)
    if (_013_) \mem[6] [0] <= din[0];
  always @(posedge clk)
    if (_013_) \mem[6] [1] <= din[1];
  always @(posedge clk)
    if (_013_) \mem[6] [2] <= din[2];
  always @(posedge clk)
    if (_013_) \mem[6] [3] <= din[3];
  always @(posedge clk)
    if (_013_) \mem[6] [4] <= din[4];
  always @(posedge clk)
    if (_013_) \mem[6] [5] <= din[5];
  always @(posedge clk)
    if (_013_) \mem[6] [6] <= din[6];
  always @(posedge clk)
    if (_013_) \mem[6] [7] <= din[7];
  always @(posedge clk)
    if (_014_) \mem[7] [0] <= din[0];
  always @(posedge clk)
    if (_014_) \mem[7] [1] <= din[1];
  always @(posedge clk)
    if (_014_) \mem[7] [2] <= din[2];
  always @(posedge clk)
    if (_014_) \mem[7] [3] <= din[3];
  always @(posedge clk)
    if (_014_) \mem[7] [4] <= din[4];
  always @(posedge clk)
    if (_014_) \mem[7] [5] <= din[5];
  always @(posedge clk)
    if (_014_) \mem[7] [6] <= din[6];
  always @(posedge clk)
    if (_014_) \mem[7] [7] <= din[7];
  always @(posedge clk)
    if (_009_) \mem[2] [0] <= din[0];
  always @(posedge clk)
    if (_009_) \mem[2] [1] <= din[1];
  always @(posedge clk)
    if (_009_) \mem[2] [2] <= din[2];
  always @(posedge clk)
    if (_009_) \mem[2] [3] <= din[3];
  always @(posedge clk)
    if (_009_) \mem[2] [4] <= din[4];
  always @(posedge clk)
    if (_009_) \mem[2] [5] <= din[5];
  always @(posedge clk)
    if (_009_) \mem[2] [6] <= din[6];
  always @(posedge clk)
    if (_009_) \mem[2] [7] <= din[7];
  always @(posedge clk)
    if (_010_) \mem[3] [0] <= din[0];
  always @(posedge clk)
    if (_010_) \mem[3] [1] <= din[1];
  always @(posedge clk)
    if (_010_) \mem[3] [2] <= din[2];
  always @(posedge clk)
    if (_010_) \mem[3] [3] <= din[3];
  always @(posedge clk)
    if (_010_) \mem[3] [4] <= din[4];
  always @(posedge clk)
    if (_010_) \mem[3] [5] <= din[5];
  always @(posedge clk)
    if (_010_) \mem[3] [6] <= din[6];
  always @(posedge clk)
    if (_010_) \mem[3] [7] <= din[7];
  always @(posedge clk)
    if (_011_) \mem[4] [0] <= din[0];
  always @(posedge clk)
    if (_011_) \mem[4] [1] <= din[1];
  always @(posedge clk)
    if (_011_) \mem[4] [2] <= din[2];
  always @(posedge clk)
    if (_011_) \mem[4] [3] <= din[3];
  always @(posedge clk)
    if (_011_) \mem[4] [4] <= din[4];
  always @(posedge clk)
    if (_011_) \mem[4] [5] <= din[5];
  always @(posedge clk)
    if (_011_) \mem[4] [6] <= din[6];
  always @(posedge clk)
    if (_011_) \mem[4] [7] <= din[7];
  always @(posedge clk)
    if (_012_) \mem[5] [0] <= din[0];
  always @(posedge clk)
    if (_012_) \mem[5] [1] <= din[1];
  always @(posedge clk)
    if (_012_) \mem[5] [2] <= din[2];
  always @(posedge clk)
    if (_012_) \mem[5] [3] <= din[3];
  always @(posedge clk)
    if (_012_) \mem[5] [4] <= din[4];
  always @(posedge clk)
    if (_012_) \mem[5] [5] <= din[5];
  always @(posedge clk)
    if (_012_) \mem[5] [6] <= din[6];
  always @(posedge clk)
    if (_012_) \mem[5] [7] <= din[7];
  always @(posedge clk)
    if (_007_) \mem[15] [0] <= din[0];
  always @(posedge clk)
    if (_007_) \mem[15] [1] <= din[1];
  always @(posedge clk)
    if (_007_) \mem[15] [2] <= din[2];
  always @(posedge clk)
    if (_007_) \mem[15] [3] <= din[3];
  always @(posedge clk)
    if (_007_) \mem[15] [4] <= din[4];
  always @(posedge clk)
    if (_007_) \mem[15] [5] <= din[5];
  always @(posedge clk)
    if (_007_) \mem[15] [6] <= din[6];
  always @(posedge clk)
    if (_007_) \mem[15] [7] <= din[7];
  always @(posedge clk)
    if (_008_) \mem[1] [0] <= din[0];
  always @(posedge clk)
    if (_008_) \mem[1] [1] <= din[1];
  always @(posedge clk)
    if (_008_) \mem[1] [2] <= din[2];
  always @(posedge clk)
    if (_008_) \mem[1] [3] <= din[3];
  always @(posedge clk)
    if (_008_) \mem[1] [4] <= din[4];
  always @(posedge clk)
    if (_008_) \mem[1] [5] <= din[5];
  always @(posedge clk)
    if (_008_) \mem[1] [6] <= din[6];
  always @(posedge clk)
    if (_008_) \mem[1] [7] <= din[7];
  always @(posedge clk)
    if (_015_) \mem[8] [0] <= din[0];
  always @(posedge clk)
    if (_015_) \mem[8] [1] <= din[1];
  always @(posedge clk)
    if (_015_) \mem[8] [2] <= din[2];
  always @(posedge clk)
    if (_015_) \mem[8] [3] <= din[3];
  always @(posedge clk)
    if (_015_) \mem[8] [4] <= din[4];
  always @(posedge clk)
    if (_015_) \mem[8] [5] <= din[5];
  always @(posedge clk)
    if (_015_) \mem[8] [6] <= din[6];
  always @(posedge clk)
    if (_015_) \mem[8] [7] <= din[7];
  always @(posedge clk)
    if (_001_) \mem[0] [0] <= din[0];
  always @(posedge clk)
    if (_001_) \mem[0] [1] <= din[1];
  always @(posedge clk)
    if (_001_) \mem[0] [2] <= din[2];
  always @(posedge clk)
    if (_001_) \mem[0] [3] <= din[3];
  always @(posedge clk)
    if (_001_) \mem[0] [4] <= din[4];
  always @(posedge clk)
    if (_001_) \mem[0] [5] <= din[5];
  always @(posedge clk)
    if (_001_) \mem[0] [6] <= din[6];
  always @(posedge clk)
    if (_001_) \mem[0] [7] <= din[7];
  always @(posedge clk)
    if (_002_) \mem[10] [0] <= din[0];
  always @(posedge clk)
    if (_002_) \mem[10] [1] <= din[1];
  always @(posedge clk)
    if (_002_) \mem[10] [2] <= din[2];
  always @(posedge clk)
    if (_002_) \mem[10] [3] <= din[3];
  always @(posedge clk)
    if (_002_) \mem[10] [4] <= din[4];
  always @(posedge clk)
    if (_002_) \mem[10] [5] <= din[5];
  always @(posedge clk)
    if (_002_) \mem[10] [6] <= din[6];
  always @(posedge clk)
    if (_002_) \mem[10] [7] <= din[7];
  always @(posedge clk)
    if (_003_) \mem[11] [0] <= din[0];
  always @(posedge clk)
    if (_003_) \mem[11] [1] <= din[1];
  always @(posedge clk)
    if (_003_) \mem[11] [2] <= din[2];
  always @(posedge clk)
    if (_003_) \mem[11] [3] <= din[3];
  always @(posedge clk)
    if (_003_) \mem[11] [4] <= din[4];
  always @(posedge clk)
    if (_003_) \mem[11] [5] <= din[5];
  always @(posedge clk)
    if (_003_) \mem[11] [6] <= din[6];
  always @(posedge clk)
    if (_003_) \mem[11] [7] <= din[7];
  always @(posedge clk)
    if (_004_) \mem[12] [0] <= din[0];
  always @(posedge clk)
    if (_004_) \mem[12] [1] <= din[1];
  always @(posedge clk)
    if (_004_) \mem[12] [2] <= din[2];
  always @(posedge clk)
    if (_004_) \mem[12] [3] <= din[3];
  always @(posedge clk)
    if (_004_) \mem[12] [4] <= din[4];
  always @(posedge clk)
    if (_004_) \mem[12] [5] <= din[5];
  always @(posedge clk)
    if (_004_) \mem[12] [6] <= din[6];
  always @(posedge clk)
    if (_004_) \mem[12] [7] <= din[7];
  always @(posedge clk)
    if (_005_) \mem[13] [0] <= din[0];
  always @(posedge clk)
    if (_005_) \mem[13] [1] <= din[1];
  always @(posedge clk)
    if (_005_) \mem[13] [2] <= din[2];
  always @(posedge clk)
    if (_005_) \mem[13] [3] <= din[3];
  always @(posedge clk)
    if (_005_) \mem[13] [4] <= din[4];
  always @(posedge clk)
    if (_005_) \mem[13] [5] <= din[5];
  always @(posedge clk)
    if (_005_) \mem[13] [6] <= din[6];
  always @(posedge clk)
    if (_005_) \mem[13] [7] <= din[7];
  always @(posedge clk)
    if (_006_) \mem[14] [0] <= din[0];
  always @(posedge clk)
    if (_006_) \mem[14] [1] <= din[1];
  always @(posedge clk)
    if (_006_) \mem[14] [2] <= din[2];
  always @(posedge clk)
    if (_006_) \mem[14] [3] <= din[3];
  always @(posedge clk)
    if (_006_) \mem[14] [4] <= din[4];
  always @(posedge clk)
    if (_006_) \mem[14] [5] <= din[5];
  always @(posedge clk)
    if (_006_) \mem[14] [6] <= din[6];
  always @(posedge clk)
    if (_006_) \mem[14] [7] <= din[7];
  always @(posedge clk)
    dout[0] <= _000_[0];
  always @(posedge clk)
    dout[1] <= _000_[1];
  always @(posedge clk)
    dout[2] <= _000_[2];
  always @(posedge clk)
    dout[3] <= _000_[3];
  always @(posedge clk)
    dout[4] <= _000_[4];
  always @(posedge clk)
    dout[5] <= _000_[5];
  always @(posedge clk)
    dout[6] <= _000_[6];
  always @(posedge clk)
    dout[7] <= _000_[7];
  always @(posedge clk)
    if (_016_) \mem[9] [0] <= din[0];
  always @(posedge clk)
    if (_016_) \mem[9] [1] <= din[1];
  always @(posedge clk)
    if (_016_) \mem[9] [2] <= din[2];
  always @(posedge clk)
    if (_016_) \mem[9] [3] <= din[3];
  always @(posedge clk)
    if (_016_) \mem[9] [4] <= din[4];
  always @(posedge clk)
    if (_016_) \mem[9] [5] <= din[5];
  always @(posedge clk)
    if (_016_) \mem[9] [6] <= din[6];
  always @(posedge clk)
    if (_016_) \mem[9] [7] <= din[7];
endmodule
